CREATE TABLE IF NOT EXISTS _Mod_WSGL_Licencas(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lic_id VARCHAR(64) NOT NULL COMMENT 'UUID publico da licenca (claim lic_id)',
    tipo VARCHAR(40) NOT NULL,
    cliente_id BIGINT NOT NULL,
    contrato_id BIGINT NULL,
    ambiente_id BIGINT NOT NULL,
    cluster_id BIGINT NOT NULL COMMENT 'FK -> _Mod_WSGL_Clusters',
    modulo VARCHAR(120) NULL,
    instancia VARCHAR(120) NULL,
    nivel VARCHAR(40) NULL,
    limites TEXT NULL COMMENT 'JSON de limites (vagas, instancias...)',
    jws MEDIUMTEXT NOT NULL COMMENT 'licenca assinada (JWS compacto EdDSA)',
    kid VARCHAR(60) NULL,
    situacao ENUM('ativa','expirada','revogada','substituida') NOT NULL DEFAULT 'ativa',
    tipo_emissao ENUM('nova','renovacao','substituicao','extensao') NOT NULL DEFAULT 'nova',
    emitida_em TIMESTAMP NULL,
    expira_em TIMESTAMP NULL,
    criado_em TIMESTAMP NULL, criado_por BIGINT NOT NULL DEFAULT 0,
    editado_em TIMESTAMP NULL, editado_por BIGINT NOT NULL DEFAULT 0,
    excluido_em TIMESTAMP NULL, excluido_por BIGINT NOT NULL DEFAULT 0,
    ativado_em TIMESTAMP NULL, ativado_por BIGINT NOT NULL DEFAULT 0,
    inativado_em TIMESTAMP NULL, inativado_por BIGINT NOT NULL DEFAULT 0,
    ativo INT(1) DEFAULT 1, excluido INT(1) DEFAULT 0,
    UNIQUE KEY uq_wsgl_licencas_lic_id (lic_id),
    INDEX idx_wsgl_licencas_cluster (cluster_id),
    INDEX idx_wsgl_licencas_situacao (situacao)
);
